SUPERHEATED_TEMP = 700
MAX_REACTOR_TEMP = 1200

TEMP_PER_SUPERHEATED_WATER = 0.15
MAX_FLOW_PER_TICK = 50
REACTOR_IN_FLOW_SIZE = 50
REACTOR_OUT_FLOW_SIZE = 50

STARTING_EFFICIENCY = 0.5
NEIGHBOR_EFFICIENCY_BONUS = 0.25
MAX_NEIGHBORS = 6
EFFICIENCY_BOOST_PER_HUNDRED_TEMP = 0.05
