require("utils")
require("from-krastorio-2")

require("data-updates.inventory-size-changes")
require("data-updates.recipe-changes")
require("data-updates.material-science-changes")
require("data-updates.tech-changes")
require("data-updates.add-steam-power")
require("data-updates.entity-changes")
require("data-updates.resource-changes")
require("data-updates.biter-changes")
require("data-updates.graphics-changes")
